#!/bin/sh
#
# This file was generated by "mbp"
#
#


#
# Converting ELF File: ../GIGLE10.elf to: "../flash/GIGLE10_epcs_flash_controller_0.flash"
#
echo Converting ELF
$SOPC_KIT_NIOS2/bin/elf2flash --input="../GIGLE10.elf" --output="../flash/GIGLE10_epcs_flash_controller_0.flash" --epcs --after="../flash/tse10G_epcs_flash_controller_0.flash" 

