#!/bin/sh
#
# This file was generated by "mbp"
#
#

#
# Converting SOF File: tse10G.sof to: "../flash/tse10G_epcs_flash_controller_0.flash"
#
#echo Converting SOF 05160C02
#$SOPC_KIT_NIOS2/bin/sof2flash --input="tse10G_05160C02.sof" --output="../flash/tse10G_epcs_flash_controller_0_C02.flash" --epcs 

#echo Converting SOF 07170C04
#$SOPC_KIT_NIOS2/bin/sof2flash --input="tse10G_07170C04.sof" --output="../flash/tse10G_epcs_flash_controller_0_C04.flash" --epcs 

echo Converting SOF 08160C05 with PPM
$SOPC_KIT_NIOS2/bin/sof2flash --input="tse10G_08160C05.sof" --output="../flash/tse10G_epcs_flash_controller_0_C05.flash" --epcs 