#!/bin/sh
#
# This file was generated by "mbp"
#
#


#
#
#
echo Erasing Entire FLASH
$SOPC_KIT_NIOS2/bin/nios2-flash-programmer --base=0x0 --epcs --device=1 --instance=0 '--cable=USB-Blaster on localhost [USB-0]' --erase-all 


