#!/bin/sh
#
# This file was generated by mbp!
#
#

#
# Programming SOF File: "../flash/tse10G_epcs_flash_controller_0.flash" To Device: epcs_flash_controller_0
#
#
#echo -e "\n-----------Programming SOF----------------------"
#$SOPC_KIT_NIOS2/bin/nios2-flash-programmer "../flash/tse10G_epcs_flash_controller_0.flash" --base=0x0 --epcs --sidp=0x1830 --id=0x9A2504 --#timestamp=1493747205 --device=1 --instance=0 '--cable=USB-Blaster on localhost [USB-0]' --program 

#
# Programming ELF File: "../flash/GIGLE10_epcs_flash_controller_0.flash" To Device: epcs_flash_controller_0
#
#
echo -e "\n-----------Programming ELF----------------------"
$SOPC_KIT_NIOS2/bin/nios2-flash-programmer "../flash/GIGLE10_epcs_flash_controller_0.flash" --base=0x0 --epcs --sidp=0x1830 --id=0x9A2504 --timestamp=1493747205 --device=1 --instance=0 '--cable=USB-Blaster on localhost [USB-0]' --program --go 

#
# Programming PHY File: "QT2x25D_module_firmware_v2_0_3_2_MDIO_epcs_flash_controller_0.flash" To Device: epcs_flash_controller_0
#
#echo -e "\n-----------Programming PHY----------------------"
#$SOPC_KIT_NIOS2/bin/nios2-flash-programmer "../flash/QT2x25D_module_firmware_v2_0_3_2_MDIO_epcs_flash_controller_0.flash" --base=0x0 --epcs --#device=1 --instance=0 '--cable=USB-Blaster on localhost [USB-0]' --program 


#
#
#
echo -e "\n-----------Programming FLASH FINISHED----------------------\n"
#