#!/bin/sh
#
# This file was generated by "mbp"
#
#


#
# Programming PHY File: "../flash/QT2x25D_module_firmware_v2_0_3_2_MDIO_epcs_flash_controller_0.flash" To Device: epcs_flash_controller_0
#
# (--sidp=0x2030 --id=0x9A2504 --timestamp=1362526322)
#
echo Programming PHY
$SOPC_KIT_NIOS2/bin/nios2-flash-programmer "../flash/QT2x25D_module_firmware_v2_0_3_2_MDIO_epcs_flash_controller_0.flash" --base=0x0 --epcs --device=1 --instance=0 '--cable=USB-Blaster on localhost [USB-0]' --program 


